# Generated by Django 5.1.2 on 2024-10-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_model',
            name='user_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
