# Generated by Django 5.1.2 on 2024-10-22 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_student_model_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_model',
            name='user_name',
        ),
    ]
