# Generated by Django 5.1.2 on 2024-10-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.PositiveIntegerField()),
                ('branch', models.CharField(choices=[('python', 'python'), ('java', 'java'), ('c++', 'c++'), ('ruby', 'ruby'), ('.net', '.net'), ('java script', 'java script')], max_length=30)),
            ],
        ),
    ]
