# Generated by Django 5.1.2 on 2024-10-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_studentmodel_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
    ]
